version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce-site
    ports:
      - "5428:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
